### PR TITLE
negated match goes into subdirectories

### LINKED ISSUE #16: Negative matches do not enter folders failing the match
I'm using recursive-readdir to get a list of files with a specific extension. I use '!*txt*' as macth. This causes folders not having 'txt' in their name to be ignored.
I was a bit surprised by this behaviour, maybe it should be documented, or the match should only be applied to files and not folders.

### PR DESCRIPTION
**Pull request by ferhatelmas**
- fixes #16

### CODE REVIEW

File: test/recursive-raddir-test.js [hunk 1]
```diff
@@ -72,4 +72,20 @@ describe('readdir', function() {
       done()
     })
   })
+
+  it('works when negated ignore list is given', function(done) {
+
+    var expectedFiles = [
+      __dirname + '/testdir/c.txt',
```
Comment (jergason) [inline test/recursive-raddir-test.js]: Can you use `path.join` instead of string concatenation so this works on windows as well?

Comment (ferhatelmas) [inline test/recursive-raddir-test.js]: sure.

do you want me to edit old test, too?

Comment (jergason) [inline test/recursive-raddir-test.js]: Oh wow, didn't notice the old tests were like that. Don't worry about that,
I'll clean up the old tests myself.
